### PR TITLE
Install script

### LINKED ISSUE #1: Install script fails: "sh: vim_config.sh: No such file or directory"
The installations instructions only download mac.sh, and not the supporting files (eg setup_the_dock.sh, vim_config.sh, etc).

This leads to errors during installation

### PR DESCRIPTION
**Pull request by ianyamey**
Inlines the installation scripts into a single `mac.sh` file

Resolves #1

### CODE REVIEW

File: install_shiftit.sh [hunk 1]
```diff
@@ -1,5 +0,0 @@
-curl -L https://raw.github.com/onsi/ShiftIt/master/ShiftIt.zip -o ShiftIt.zip
-unzip ShiftIt.zip ShiftIt.app/* -d /Applications/
-rm ShiftIt.zip
-
-open /Applications/ShiftIt.app/
```
Comment (j-clark) [inline install_shiftit.sh:5]: this is a fork that add features like multiple window sizes, that isn't available in the main branch (the one on homebrew), so i'd prefer to continue to use this

Comment (ianyamey) [inline install_shiftit.sh:5]: No worries. Fixed in aca3404a9c7ee986336e8513af89faea08488740
